# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

spqrs <- function(response, predictor, tau, degree, dimension = 10L, tau_penalty = 0.5, number_lambdas = 3L, lambda_max = 1e+2, epsilon_lambda = 1e-10, maxiter = 500L, epsilon_iterations = 1e-6, non_crossing = FALSE) {
    .Call(`_spqrs_spqrs`, response, predictor, tau, degree, dimension, tau_penalty, number_lambdas, lambda_max, epsilon_lambda, maxiter, epsilon_iterations, non_crossing)
}

bsplines <- function(x, t, degree = 1L, derivative = 0L) {
    .Call(`_spqrs_bsplines`, x, t, degree, derivative)
}

bspline <- function(x, t, degree = 1L, j = 0L, derivative = 0L) {
    .Call(`_spqrs_bspline`, x, t, degree, j, derivative)
}

bsp <- function(x, t, degree, j) {
    .Call(`_spqrs_bsp`, x, t, degree, j)
}

dbsp <- function(x, t, degree, j, derivative) {
    .Call(`_spqrs_dbsp`, x, t, degree, j, derivative)
}

jump_bsplines <- function(t, degree = 1L) {
    .Call(`_spqrs_jump_bsplines`, t, degree)
}

knots2t <- function(knots, degree = 1L) {
    .Call(`_spqrs_knots2t`, knots, degree)
}

dim2knots <- function(predictor, dimension, degree) {
    .Call(`_spqrs_dim2knots`, predictor, dimension, degree)
}

lambdas_all <- function(response, number_lambdas, lambda_max, epsilon_lambda) {
    .Call(`_spqrs_lambdas_all`, response, number_lambdas, lambda_max, epsilon_lambda)
}

check <- function(u, tau) {
    .Call(`_spqrs_check`, u, tau)
}

Check <- function(v, tau) {
    .Call(`_spqrs_Check`, v, tau)
}

NumericVectors <- function(size) {
    .Call(`_spqrs_NumericVectors`, size)
}

IntegerVectors <- function(size) {
    .Call(`_spqrs_IntegerVectors`, size)
}

support_of_vector <- function(v) {
    .Call(`_spqrs_support_of_vector`, v)
}

find_solution <- function(v, w, tau, tau_penalty, lambda, a, c, pen_type) {
    .Call(`_spqrs_find_solution`, v, w, tau, tau_penalty, lambda, a, c, pen_type)
}

find_slope_v <- function(v, w, tau, tau_penalty, lambda, a, c, i, pen_type) {
    .Call(`_spqrs_find_slope_v`, v, w, tau, tau_penalty, lambda, a, c, i, pen_type)
}

find_slope_c <- function(v, w, tau, tau_penalty, lambda, a, c, l, pen_type) {
    .Call(`_spqrs_find_slope_c`, v, w, tau, tau_penalty, lambda, a, c, l, pen_type)
}

type_forward <- function(target, tau_penalty, lambda, a, c) {
    .Call(`_spqrs_type_forward`, target, tau_penalty, lambda, a, c)
}

type_backward <- function(target, tau_penalty, lambda, a, c) {
    .Call(`_spqrs_type_backward`, target, tau_penalty, lambda, a, c)
}

find_interval <- function(y, z) {
    .Call(`_spqrs_find_interval`, y, z)
}

find_interval_weight <- function(w, tau) {
    .Call(`_spqrs_find_interval_weight`, w, tau)
}

bubble_order <- function(vec) {
    .Call(`_spqrs_bubble_order`, vec)
}

subsetNumVec <- function(x, index) {
    .Call(`_spqrs_subsetNumVec`, x, index)
}

subsetIntVec <- function(x, index) {
    .Call(`_spqrs_subsetIntVec`, x, index)
}

